import { ethers } from "hardhat";
import * as fs from "fs";
import * as path from "path";

async function main() {
    const [deployer] = await ethers.getSigners();
    console.log("Deploying contracts with account:", deployer.address);
    console.log("Balance:", ethers.utils.formatEther(await deployer.getBalance()), "MON");

    // Deploy MonadMarketplace
    const MarketplaceFactory = await ethers.getContractFactory("MonadMarketplace");
    const marketplace = await MarketplaceFactory.deploy({ gasLimit: 5000000 });
    await marketplace.deployed();
    console.log("MonadMarketplace deployed to:", marketplace.address);

    // Deploy LendingPool
    const PoolFactory = await ethers.getContractFactory("LendingPool");
    const pool = await PoolFactory.deploy({ gasLimit: 3000000 });
    await pool.deployed();
    console.log("LendingPool deployed to:", pool.address);

    // Wire up: pool <-> marketplace
    await (await pool.setMarketplace(marketplace.address)).wait();
    await (await marketplace.setLendingPool(pool.address)).wait();
    console.log("Contracts wired: pool <-> marketplace");

    // Read ABIs
    const frontendLibDir = path.join(__dirname, "../../src/lib");
    if (!fs.existsSync(frontendLibDir)) {
        fs.mkdirSync(frontendLibDir, { recursive: true });
    }

    const marketplaceArtifact = JSON.parse(
        fs.readFileSync(
            path.join(__dirname, "../artifacts/contracts/MonadMarketplace.sol/MonadMarketplace.json"),
            "utf8"
        )
    );
    const poolArtifact = JSON.parse(
        fs.readFileSync(
            path.join(__dirname, "../artifacts/contracts/LendingPool.sol/LendingPool.json"),
            "utf8"
        )
    );

    // Write contract.ts (marketplace)
    const contractTs = `// Auto-generated by deployMarketplace.ts — do not edit manually
export const MARKETPLACE_ADDRESS = "${marketplace.address}" as const;

export const MARKETPLACE_ABI = ${JSON.stringify(marketplaceArtifact.abi, null, 2)} as const;
`;
    fs.writeFileSync(path.join(frontendLibDir, "contract.ts"), contractTs);

    // Write lendingPool.ts (pool)
    const poolTs = `// Auto-generated by deployMarketplace.ts — do not edit manually
export const LENDING_POOL_ADDRESS = "${pool.address}" as const;

export const LENDING_POOL_ABI = ${JSON.stringify(poolArtifact.abi, null, 2)} as const;

export const LOAN_STATUS = ["Active", "Paid", "Defaulted"] as const;
export const INTEREST_RATE_BPS = 500n;
export const LTV_BPS = 7000n;
`;
    fs.writeFileSync(path.join(frontendLibDir, "lendingPool.ts"), poolTs);

    console.log("\nABIs + addresses saved to src/lib/");
    console.log("\n=== Deployment Summary ===");
    console.log(`Network:          ${(await ethers.provider.getNetwork()).name}`);
    console.log(`MonadMarketplace: ${marketplace.address}`);
    console.log(`LendingPool:      ${pool.address}`);
    console.log(`Deployer:         ${deployer.address}`);
}

main()
    .then(() => process.exit(0))
    .catch((error) => {
        console.error(error);
        process.exit(1);
    });
